/**
 * Marginalia Obsidian/Markdown Export
 *
 * Builds interlinked markdown files from all readings, highlights, and tags,
 * then packages them as a .zip for Obsidian-compatible vaults.
 *
 * Exposed as window.__marginaliaExport = { exportToObsidian }.
 * Depends on JSZip being loaded globally before this script.
 *
 * Reading markdown is generated by the shared lib/markdown-export.js module;
 * this file only handles tag indexes, master index, and ZIP packaging.
 */
(function () {
  'use strict';

  // ── Tag index file ──────────────────────────────────────────────
  function buildTagIndex(tag, slugify, yamlEscape, readingsWithTag) {
    var lines = [
      '---',
      'tag: ' + yamlEscape(tag),
      'type: "tag-index"',
      '---',
      '',
      '# ' + tag,
      '',
      readingsWithTag.length + ' reading' + (readingsWithTag.length !== 1 ? 's' : '') + ' with this tag.',
      ''
    ];
    // Sort by title
    readingsWithTag.sort(function (a, b) {
      return (a.title || '').localeCompare(b.title || '');
    });
    for (var i = 0; i < readingsWithTag.length; i++) {
      var r = readingsWithTag[i];
      var slug = slugify(r.title);
      lines.push('- [[' + slug + '|' + (r.title || 'Untitled') + ']]');
    }
    lines.push('');
    return lines.join('\n');
  }

  // ── Master index ─────────────────────────────────────────────────
  function buildMasterIndex(readings, tagList, slugify) {
    var lines = [
      '---',
      'type: "index"',
      '---',
      '',
      '# Marginalia Reading Index',
      '',
      readings.length + ' reading' + (readings.length !== 1 ? 's' : '') + ' exported.',
      '',
      '## Readings',
      ''
    ];
    // Sort by title
    var sorted = readings.slice().sort(function (a, b) {
      return (a.title || '').localeCompare(b.title || '');
    });
    for (var i = 0; i < sorted.length; i++) {
      var r = sorted[i];
      var slug = slugify(r.title);
      var author = r.author ? ' — ' + r.author : '';
      lines.push('- [[' + slug + '|' + (r.title || 'Untitled') + ']]' + author);
    }

    if (tagList.length) {
      lines.push('');
      lines.push('## Tags');
      lines.push('');
      tagList.sort();
      for (var j = 0; j < tagList.length; j++) {
        var tSlug = slugify(tagList[j]);
        lines.push('- [[' + tSlug + '|' + tagList[j] + ']]');
      }
    }

    lines.push('');
    return lines.join('\n');
  }

  // ── Main export function ─────────────────────────────────────────
  async function exportToObsidian() {
    // Dynamic import of shared markdown module (keeps IIFE pattern intact)
    // Resolve relative to HTML document root, not this script's directory
    var md = await import('./lib/markdown-export.js');
    var slugify = md.slugify;
    var yamlEscape = md.yamlEscape;
    var buildMarkdownForReading = md.buildMarkdownForReading;

    // 1. Load all readings
    var storageResult = await chrome.storage.local.get('ocReadings');
    var ocReadings = storageResult.ocReadings || {};
    var pageKeys = Object.keys(ocReadings);

    if (!pageKeys.length) {
      throw new Error('No readings found to export.');
    }

    // 2. Load all highlights in one batch
    var hlData = pageKeys.length ? await chrome.storage.local.get(pageKeys) : {};

    // 3. Build slug -> reading map and collect all data
    var slugMap = {};     // slug -> reading object
    var readingsList = []; // array of { reading, highlights, slug }
    var tagReadings = {}; // tag -> [reading, ...]

    for (var i = 0; i < pageKeys.length; i++) {
      var pk = pageKeys[i];
      var reading = ocReadings[pk];
      var highlights = Array.isArray(hlData[pk]) ? hlData[pk] : [];
      var slug = slugify(reading.title);

      slugMap[slug] = reading;
      readingsList.push({ reading: reading, highlights: highlights, slug: slug });

      // Collect tag -> readings mapping
      if (reading.tags) {
        for (var t = 0; t < reading.tags.length; t++) {
          var tag = reading.tags[t];
          if (!tagReadings[tag]) tagReadings[tag] = [];
          tagReadings[tag].push(reading);
        }
      }
    }

    // 4. Build zip
    var zip = new JSZip();

    // Individual reading files (uses shared module)
    for (var r = 0; r < readingsList.length; r++) {
      var entry = readingsList[r];
      var content = buildMarkdownForReading(entry.reading, entry.highlights, slugMap);
      zip.file('readings/' + entry.slug + '.md', content);
    }

    // Tag index files
    var tagList = Object.keys(tagReadings);
    for (var ti = 0; ti < tagList.length; ti++) {
      var tagName = tagList[ti];
      var tagSlug = slugify(tagName);
      var tagContent = buildTagIndex(tagName, slugify, yamlEscape, tagReadings[tagName]);
      zip.file('tags/' + tagSlug + '.md', tagContent);
    }

    // Master index
    var allReadingsForIndex = readingsList.map(function (e) { return e.reading; });
    zip.file('index.md', buildMasterIndex(allReadingsForIndex, tagList, slugify));

    // 5. Generate and trigger download
    var blob = await zip.generateAsync({ type: 'blob' });
    var url = URL.createObjectURL(blob);
    var a = document.createElement('a');
    a.href = url;
    a.download = 'marginalia-export-' + new Date().toISOString().slice(0, 10) + '.zip';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    return readingsList.length;
  }

  window.__marginaliaExport = { exportToObsidian: exportToObsidian };
})();
